dist: xenial
sudo: required

install:
  - docker pull tutum/ubuntu:trusty
  - docker run -d -p 2222:22 -e ROOT_PASS="somepassword" tutum/ubuntu:trusty
  - wget https://launchpad.net/ubuntu/+source/libgpg-error/1.32-1/+build/15118612/+files/libgpg-error0_1.32-1_amd64.deb
  - sudo dpkg -i libgpg-error0_1.32-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libgcrypt20/1.8.3-1ubuntu1/+build/15106861/+files/libgcrypt20_1.8.3-1ubuntu1_amd64.deb
  - sudo dpkg -i libgcrypt20_1.8.3-1ubuntu1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libssh2/1.8.0-2/+build/15151524/+files/libssh2-1_1.8.0-2_amd64.deb
  - sudo dpkg -i libssh2-1_1.8.0-2_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libgpg-error/1.32-1/+build/15118612/+files/libgpg-error-dev_1.32-1_amd64.deb
  - sudo dpkg -i libgpg-error-dev_1.32-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libgcrypt20/1.8.3-1ubuntu1/+build/15106861/+files/libgcrypt20-dev_1.8.3-1ubuntu1_amd64.deb
  - sudo dpkg -i libgcrypt20-dev_1.8.3-1ubuntu1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libssh2/1.8.0-2/+build/15151524/+files/libssh2-1-dev_1.8.0-2_amd64.deb
  - sudo dpkg -i libssh2-1-dev_1.8.0-2_amd64.deb
  - shards install
  - sleep 5

script:
  - crystal spec
  - bin/ameba

language: crystal
